const $=(s)=>document.querySelector(s);let activeCategory="Todos";let searchTerm="";
function money(p){return `${p.currency||"Bs"} ${p.price}`}function whatsappLink(m){return `https://wa.me/${STORE_CONFIG.whatsappNumber}?text=${encodeURIComponent(m)}`}function productUrl(p){return `#producto/${p.id}`}
function imageBlock(p,c="product-image"){return p.image?`<div class="${c}"><img src="${p.image}" alt="${p.name}"></div>`:`<div class="${c}">${p.name}</div>`}
function setupStoreConfig(){document.title=STORE_CONFIG.pageTitle||STORE_CONFIG.storeName;$("#storeLogo").textContent=STORE_CONFIG.storeName;$("#heroTag").textContent=STORE_CONFIG.heroTag;$("#heroTitle").textContent=STORE_CONFIG.heroTitle;$("#heroText").textContent=STORE_CONFIG.heroText;$("#heroCardTitle").textContent=STORE_CONFIG.heroCardTitle;$("#heroCardText").textContent=STORE_CONFIG.heroCardText;$("#helpTitle").textContent=STORE_CONFIG.helpTitle;$("#helpText").textContent=STORE_CONFIG.helpText;$("#footerStoreName").textContent=STORE_CONFIG.storeName;$("#footerDescription").textContent=STORE_CONFIG.footerDescription;const wa=whatsappLink(`Hola, quiero consultar el catálogo de ${STORE_CONFIG.storeName}.`);$("#headerWhatsapp").href=wa;$("#helpWhatsapp").href=wa;$("#footerWhatsapp").href=wa;$("#footerInstagram").href=STORE_CONFIG.instagramUrl||"#";$("#footerTiktok").href=STORE_CONFIG.tiktokUrl||"#"}
function renderCategories(){const grid=$("#categoryGrid");grid.innerHTML=STORE_CONFIG.categories.map(c=>`<article class="category-card" data-category="${c.filter}"><div class="icon">${c.icon}</div><h3>${c.name}</h3><p>${c.description}</p></article>`).join("");grid.querySelectorAll(".category-card").forEach(card=>card.addEventListener("click",()=>{activeCategory=card.dataset.category;location.hash="#tienda";renderFilters();renderProducts()}))}
function getCategoriesFromProducts(){return ["Todos",...new Set(PRODUCTS.map(p=>p.category))]}function renderFilters(){const tabs=$("#filterTabs");tabs.innerHTML=getCategoriesFromProducts().map(c=>`<button class="filter-tab ${c===activeCategory?"active":""}" data-category="${c}">${c}</button>`).join("");tabs.querySelectorAll(".filter-tab").forEach(b=>b.addEventListener("click",()=>{activeCategory=b.dataset.category;renderFilters();renderProducts()}))}
function getFilteredProducts(){return PRODUCTS.filter(p=>{const cat=activeCategory==="Todos"||p.category===activeCategory;const hay=[p.name,p.category,p.shortDescription,p.description,...(p.sizes||[]),...(p.colors||[]),...(p.features||[])].join(" ").toLowerCase();return cat&&hay.includes(searchTerm.toLowerCase())})}
function productCard(p){return `<a class="product-card" href="${productUrl(p)}">${imageBlock(p)}<div class="product-body"><div class="product-meta"><span class="badge">${p.badge}</span><span>${p.category}</span></div><h3 class="product-title">${p.name}</h3><p class="product-description">${p.shortDescription}</p><div class="product-bottom"><span class="price">${money(p)}</span><span class="link-more">Ver ficha →</span></div></div></a>`}
function renderProducts(){const ps=getFilteredProducts();$("#productGrid").innerHTML=ps.length?ps.map(productCard).join(""):`<div class="spec-card"><h3>No se encontraron productos</h3><p>Prueba con otra palabra o categoría.</p></div>`}
function renderBenefits(){$("#benefitGrid").innerHTML=STORE_CONFIG.benefits.map(b=>`<article class="benefit-card"><h3>${b.title}</h3><p>${b.text}</p></article>`).join("")}
function renderProductDetail(p){$("#breadcrumbProduct").textContent=p.name;$("#detailCategory").textContent=p.category;$("#detailName").textContent=p.name;$("#detailDescription").textContent=p.description;$("#detailPrice").textContent=money(p);$("#detailBadge").textContent=p.stock||p.badge;$("#detailImage").outerHTML=imageBlock(p,"product-image-large");const gallery=p.gallery&&p.gallery.length?p.gallery:[p.image].filter(Boolean);$("#thumbnailRow").innerHTML=gallery.length?gallery.map((img,i)=>`<button class="thumb" data-img="${img}" aria-label="Imagen ${i+1}"><img src="${img}" alt="${p.name} ${i+1}"></button>`).join(""):`<div class="thumb">${p.category}</div>`;$("#thumbnailRow").querySelectorAll(".thumb[data-img]").forEach(t=>t.addEventListener("click",()=>{$(".product-image-large").innerHTML=`<img src="${t.dataset.img}" alt="${p.name}">`}));$("#detailSizes").innerHTML=p.sizes.map(s=>`<span class="pill">${s}</span>`).join("");$("#detailColors").innerHTML=p.colors.map(c=>`<span class="pill">${c}</span>`).join("");$("#detailFeatures").innerHTML=p.features.map(f=>`<li>${f}</li>`).join("");$("#detailSpecs").innerHTML=Object.entries(p.specs||{}).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join("");$("#detailMeasures tbody").innerHTML=p.measurements.map(r=>`<tr><td>${r.size}</td><td>${r.width}</td><td>${r.length}</td></tr>`).join("");$("#detailWhatsapp").href=whatsappLink(`Hola, quiero consultar esta prenda: ${p.name}. Precio: ${money(p)}. ¿Está disponible?`);const related=PRODUCTS.filter(i=>i.id!==p.id&&i.category===p.category).slice(0,3);const fallback=PRODUCTS.filter(i=>i.id!==p.id).slice(0,3);$("#relatedGrid").innerHTML=(related.length?related:fallback).map(productCard).join("")}
function showHome(){$("#homeView").hidden=false;$("#productView").hidden=true}function showProduct(id){const p=PRODUCTS.find(i=>i.id===id);if(!p){location.hash="#tienda";return}$("#homeView").hidden=true;$("#productView").hidden=false;renderProductDetail(p);window.scrollTo({top:0,behavior:"smooth"})}
function router(){const hash=location.hash||"#inicio";if(hash.startsWith("#producto/")){showProduct(hash.replace("#producto/",""));return}showHome();if(hash==="#tienda")setTimeout(()=>document.querySelector("#tienda")?.scrollIntoView({behavior:"smooth"}),20)}
function setupSearch(){$("#searchInput").addEventListener("input",e=>{searchTerm=e.target.value;renderProducts()})}function init(){setupStoreConfig();renderCategories();renderFilters();renderProducts();renderBenefits();setupSearch();router();window.addEventListener("hashchange",router)}init();
